sudo: false
language: elixir
elixir:
  - "1.7"
  - "1.8"
  - "1.9"

services:
  - postgresql

before_script:
  - psql -c 'create database ecto_test;' -U postgres

jobs:
  include:
    - script: MIX_ENV=test mix do deps.get, compile, coveralls.travis
    - script: mix credo --strict
